name: tests

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.mod
      - name: Test
        run: go test -race ./...
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build ./cmd/exordos-iam-cache
